### ISSUE TITLE
Ask somebody to continue

### ISSUE THREAD

**Issue by debian-user-france1** [evilsocket/pwnagotchi#1063]
I see that there's not much activity on this project anymore.. Would you @evilsocket ask somebody to continue the project? 
There was no update since 8 months.. Quite a lot

I personally don't want to continue that project, but in order to grow the project again we need more updates, make it smarter so the people that got bored come again and help.

**Comment by evilsocket** [comment]
@debian-user-france1 anyone can send a PR and I periodically merge the ones I think add value to the project. Github issues can be used to discuss ideas and generally where the project direction is. There's nothing to ask to anybody because the problem is not who "owns" the repo. The simple truth is that people enjoy free software but are not willing to help. 

Let's take your last sentence as an example:

> I personally don't want to continue that project, but in order to grow the project again we need more updates

This represents what I read 99.9999% of the times when somebody asks for something in open source software. It's all about demanding updates and new features to "make it smarter so that people that got bored come again and help" (as if they were doing me a favor in working on something they use and enjoy as well :D), but when it comes to **actually** helping, nobody really wants :D 

Check the PRs, it's mostly very minor stuff and fixes, nobody is willing to put some actual work and new code in it. Which is fine, nobody's here is paid for it. 

Since this is not the first time you mention here how the project is idle and more or less subtly imply how things would be better in a different setup, I would suggest to avoid this for as long as you are not willing to contribute yourself.

Ciao.
