### ISSUE TITLE
pwnagotchi's web UI refuses the connection

### ISSUE THREAD

**Issue by FerdinandoPH** [evilsocket/pwnagotchi#768]
When I try to connect to the web UI, I get an error saying that the pwnagotchi refused the connection. Why does this happen?

**Comment by H4ck3r404** [comment]
What kind od setup are you using?

**Comment by FerdinandoPH** [comment]
I'm using a Raspberry Pi 4B, with a 16GB SD card.

**Comment by H4ck3r404** [comment]
Does error ocured during pairing by bluetoothctl?
What kind od error was it?
And can you post your config file?

**Comment by H4ck3r404** [comment]
Post your config file and details about connection. (ssh and page that you were connecting to)

**Comment by FerdinandoPH** [comment]
Iḿ trying to connect to http://pwnagotchi.local:8080/
This is my config.yml
`main:
	name: 'pwnagotchifph'
	whitelist:
		- 'WIFI_FERINAL_CENTRAL'
		- 'WIFI_FERINAL_CENTRAL_PLUS'
		- 'WIFI_FERINAL'
		- 'vodafone E3D4'
	plugins:
		gps:
			enabled: true
		auto-update:
			enabled: true
		memtemp:
			enabled: true
		net-pos:
			enabled: true
		onlinehashcrack:
			enabled: true
		quickdic: 
			enabled: true
			wordlist_folder: /home/pi/Probable-Wordlists-master
		webcfg:
			enabled: true
		bt-tether:
			enabled: true
			devices:
				Oneplus6TFPH:
					enabled: true
					search order: 1
					mac: '64:a2:f9:f4:fe:4a'
					ip: '192.168.44.44'
					netmask: 24
					interval: 1
					scantime: 15
					share_internet: true
					priority: 99
					max_tries: 5
		webgpsmap:
			enabled: true
		grid:
			enabled: true
			report: true
			exclude:
				- 'vodafoneE3D4'

ui:
	web:
		enabled: true
		username: pi
		password: raspberry`

**Comment by H4ck3r404** [comment]
Try connecting to 192.168.44.44:8080

**Comment by phr34k0** [comment]
I had the same issue while I was abroad and it works when I was back in my own country. I get that "connection error" that prints on the page instead of the webui. Apparently solved it with having Zerotier installed, turning on bridging on my home computers and changing my DNS to that of Google DNS (8.8.8.8, 8.8.4.4) worked. 

Got to know that the place I was at has DNS resolving issues that caused the internet itself to be super slow while browsing some other sites.

**Comment by dadav** [comment]
Derek close
